language: cpp

services:
  - docker

env:
  matrix:
    - FLAVOR=COMPANION
    - FLAVOR=ARM9X
    - FLAVOR=X9LITE
    - FLAVOR=X7
    - FLAVOR=XLITE
    - FLAVOR=X9
    - FLAVOR=COLORLCD

before_install:
  - docker pull ghcr.io/raphaelcoeffic/opentx-commit-tests

script:
  - docker run --rm --env FLAVOR=$FLAVOR -v $(pwd):/src ghcr.io/raphaelcoeffic/opentx-commit-tests
